// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suxllifgyofcdtjoddan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eGxsaWZneW9mY2R0am9kZGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzE0NjYsImV4cCI6MjA3NDQ0NzQ2Nn0.Na3lecZzhYAwcMOp686kveuTf0F95xAjZPTn61DRs3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});